dist: xenial

git:
  depth: 1

addons:
  apt:
    packages:
      - docker-ce
  
env:
  - DOCKER_CLI_EXPERIMENTAL=enabled

before_install:
  - apt-get update && apt-get install wget -y
  - wget https://github.com/docker/buildx/releases/download/v0.3.1/buildx-v0.3.1.linux-amd64 -O ~/.docker/cli-plugins/docker-buildx
  - chmod a+x ~/.docker/cli-plugins/docker-buildx
  
install:
  docker buildx build . --platform linux/amd64, linux/arm, linux/arm64
